site_name: My Wallet
theme: readthedocs
docs_dir: 'docs'
repo_url: https://github.com/gdi3d/my_wallet
site_url: https://gdi3d.github.io/my_wallet

pages:
- ['index.md', 'Home']
- ['getting-started.md', 'Quick Start', 'Getting Started']
- ['api-overview.md', 'API', 'Overview']
- ['api-login.md', 'API', 'Login']
- ['api-registration.md', 'API', 'Registration']
- ['api-reset-password.md', 'API', 'Reset Password']
- ['api-transactions.md', 'API', 'Transactions']
- ['api-wallets.md', 'API', 'Wallets']
- ['api-category.md', 'API', 'Categories']